{ pkgs, inputs, ... }:
let
  zoomPkgs = import inputs.nixpkgs-zoom {
    system = "x86_64-linux";
    config.allowUnfree = true;
  };
in
{
  home.packages = with pkgs; [
    autotiling
    avizo
    bc                                        # for $BIN_DIR/calc
    brightnessctl
    buf
    clipman
    ctlptl
    dante
    dbeaver-bin
    diffstat
    docker-compose
    element-desktop
    entr
    eog
    evince
    eza
    gimp
    gnupg
    google-chrome
    grim
    grpcurl
    i3-ratiosplit
    imv
    kind
    kubectx
    kubernetes-helm
    ledger-live-desktop
    libreoffice
    maim
    nautilus
    networkmanager_dmenu
    nixfmt-rfc-style
    nixpkgs-review
    nodejs
    prototool
    pulumi-bin
    python3
    readline
    slack
    slurp
    ssh-agents
    swaybg
    swayidle
    swaylock
    system-san-francisco-font
    sysz
    tdesktop
    tilt
    tmux-sessionizer
    tmuxinator
    tree
    typescript
    vanilla-dmz
    w3m
    waybar
    wf-recorder
    wl-clipboard
    wmctrl
    wtype
    xdg-utils
    yarn
    yq
    zoomPkgs.zoom-us
  ];
}
