#!/usr/bin/env bash

selection=$(fuzzel -d < "$XDG_CONFIG_HOME/qutebrowser/quickmarks")
if [ -z "$selection" ]; then
    exit 0
fi
second=$(echo $selection | awk '{print $2}')
# no second word? then this is a one-word search
if [ -z "$second" ]; then
    qutebrowser $selection
    exit 0
fi
# assume this was a selection from the menu
if [[ $second == http* ]]; then
    qutebrowser "$second"
    exit 0
fi
# otherwise we've got a multi-word web-search
qutebrowser "$selection"
